Task revision/alert feauture
Hunter27/WaterLog-Front-end pull request #73
Opened 2019-02-20 15:10 UTC by MsweliP

Implements Tank Graph and  Tank Component.

2019-02-20 15:28 UTC, FredJEhlers requested changes

2019-02-20 15:28 UTC, FredJEhlers commented on waterlog/src/App.scss
> +    margin: 20px;
inconsistent indentations

2019-02-20 15:28 UTC, FredJEhlers commented on waterlog/src/Components/DailyWastage.js
> +  console.log(props);
remove console logs

2019-02-20 15:28 UTC, FredJEhlers commented on waterlog/src/Components/DailyWastage.js
> +  console.log(props);
in all files

2019-02-20 15:28 UTC, FredJEhlers commented on waterlog/src/Components/TankComponent.js
> +				    <p>{level.instruction}</p>
inconsistent indentations

2019-02-20 15:28 UTC, FredJEhlers commented on waterlog/src/Components/TankGraph.js
> +  datasets: [
inconsistent indentation vs ` waterlog/src/Components/TankComponent.js`

2019-02-20 15:28 UTC, FredJEhlers commented on waterlog/src/Components/Wastage.js
> +		const { dailyError, dailyLoading, dailyWaste,monthlyError,monthlyWaste,monthlyLoading,seasonalError,seasonalLoading,seasonWaste } = this.props;
split over multiple lines

2019-02-20 15:28 UTC, FredJEhlers commented on waterlog/src/Stylesheets/_tank.scss
> +}
empty line at eof

2019-02-20 15:28 UTC, FredJEhlers commented on waterlog/src/Stylesheets/_tank.scss
> +}
ensure this across all files

2019-02-20 15:28 UTC, FredJEhlers commented on waterlog/src/actions/Types_BACKUP_15920.js
> +export const FETCH_SENSORS = 'FETCH_SENSORS';
why you committing this file

2019-02-20 15:28 UTC, FredJEhlers commented on waterlog/src/actions/Types_BASE_15920.js
> +export const FETCH_SENSORS = 'FETCH_SENSORS';
why are you committing this file

2019-02-20 15:28 UTC, FredJEhlers commented on waterlog/src/actions/Types_LOCAL_15920.js
> +export const FETCH_SENSORS = 'FETCH_SENSORS';
why are you committing this file

2019-02-20 15:28 UTC, FredJEhlers commented on waterlog/src/actions/Types_LOCAL_15920.js
> +//export const FETCH_WASTAGE_MONTHLY_BEGIN = "FETCH_WASTAGE_MONTHLY_BEGIN";
gc

2019-02-20 15:28 UTC, FredJEhlers commented on waterlog/src/actions/Types_REMOTE_15920.js
> +export const FETCH_SENSORS = 'FETCH_SENSORS';
why are you committing this

2019-02-20 15:28 UTC, FredJEhlers commented on waterlog/src/actions/WastageDaily.js
> +//import { FETCH_WASTAGE_DAILY, FETCH_WASTAGE_MONTHLY , FETCH_WASTAGE_SEASONALLY, FETCH_WASTAGE_DAILY_BEGIN, FETCH_WASTAGE_DAILY_FAILURE, FETCH_WASTAGE_DAILY_SUCCESS} from "./Types";
gc

2019-02-21 07:07 UTC, FredJEhlers commented on waterlog/src/Components/DailyWastage.js
> +      <div className="head"><b>R {(Math.round(sum * Globals.WATER_COST))}</b><b className="dailysubhead"> lost so far</b></div>
Inconsistent indentation

2019-02-21 07:07 UTC, FredJEhlers commented on waterlog/src/actions/WastageMonthly.js
> +//import { FETCH_WASTAGE_DAILY, FETCH_WASTAGE_MONTHLY , FETCH_WASTAGE_SEASONALLY, FETCH_WASTAGE_DAILY_BEGIN, FETCH_WASTAGE_DAILY_FAILURE, FETCH_WASTAGE_DAILY_SUCCESS} from "./Types";
GC

2019-02-21 07:07 UTC, FredJEhlers commented on waterlog/src/actions/WastageSeasonally.js
> +//import { FETCH_WASTAGE_DAILY, FETCH_WASTAGE_MONTHLY , FETCH_WASTAGE_SEASONALLY, FETCH_WASTAGE_DAILY_BEGIN, FETCH_WASTAGE_DAILY_FAILURE, FETCH_WASTAGE_DAILY_SUCCESS} from "./Types";
GC

2019-02-21 07:07 UTC, FredJEhlers commented on waterlog/src/reducers/WastageGraphMonthlyReducer.js
> +import { FETCH_WASTAGE_MONTHLY_BEGIN,FETCH_WASTAGE_MONTHLY_SUCCESS,FETCH_WASTAGE_MONTHLY_FAILURE } from '../actions/Types';
Split over multiple lines

2019-02-21 07:07 UTC, FredJEhlers commented on waterlog/src/reducers/WastageGraphSeasonallyReducer.js
> +import { FETCH_WASTAGE_SEASONALLY_BEGIN,FETCH_WASTAGE_SEASONALLY_SUCCESS,FETCH_WASTAGE_SEASONALLY_FAILURE } from '../actions/Types';
Split over multiple lines

2019-02-21 07:29 UTC, MsweliP commented on waterlog/src/reducers/WastageGraphSeasonallyReducer.js
> +import { FETCH_WASTAGE_SEASONALLY_BEGIN,FETCH_WASTAGE_SEASONALLY_SUCCESS,FETCH_WASTAGE_SEASONALLY_FAILURE } from '../actions/Types';
Done

2019-02-21 07:29 UTC, MsweliP commented on waterlog/src/reducers/WastageGraphMonthlyReducer.js
> +import { FETCH_WASTAGE_MONTHLY_BEGIN,FETCH_WASTAGE_MONTHLY_SUCCESS,FETCH_WASTAGE_MONTHLY_FAILURE } from '../actions/Types';
Done

2019-02-21 07:29 UTC, MsweliP commented on waterlog/src/actions/WastageSeasonally.js
> +//import { FETCH_WASTAGE_DAILY, FETCH_WASTAGE_MONTHLY , FETCH_WASTAGE_SEASONALLY, FETCH_WASTAGE_DAILY_BEGIN, FETCH_WASTAGE_DAILY_FAILURE, FETCH_WASTAGE_DAILY_SUCCESS} from "./Types";
Done

2019-02-21 07:29 UTC, MsweliP commented on waterlog/src/actions/WastageMonthly.js
> +//import { FETCH_WASTAGE_DAILY, FETCH_WASTAGE_MONTHLY , FETCH_WASTAGE_SEASONALLY, FETCH_WASTAGE_DAILY_BEGIN, FETCH_WASTAGE_DAILY_FAILURE, FETCH_WASTAGE_DAILY_SUCCESS} from "./Types";
Done

2019-02-21 07:29 UTC, MsweliP commented on waterlog/src/Components/DailyWastage.js
> +      <div className="head"><b>R {(Math.round(sum * Globals.WATER_COST))}</b><b className="dailysubhead"> lost so far</b></div>
Done

2019-02-21 07:44 UTC, FredJEhlers commented on waterlog/src/Components/TankComponent.js
> +<<<<<<< HEAD
You need to clean up the code here from your merge conflicts

2019-02-21 07:44 UTC, FredJEhlers commented on waterlog/src/actions/Types.js
> +<<<<<<< HEAD
You need to clean up the code here from your merge conflicts

2019-02-21 07:44 UTC, FredJEhlers commented on waterlog/src/actions/WastageDaily.js
> +<<<<<<< HEAD
You need to clean up the code here from your merge conflicts

2019-02-21 07:56 UTC, FredJEhlers approved these changes

2019-02-21 08:04 UTC, merged